# Generated by Django 5.2.5 on 2025-11-30 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_avance', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('EN_PAUSA', 'En pausa'), ('FINALIZADO', 'Finalizado')], default='EN_PROCESO', max_length=20)),
                ('descripcion', models.TextField(help_text='Tareas realizadas, observaciones, etc.')),
                ('tiempo_ejecucion_minutos', models.PositiveIntegerField(default=0, help_text='Tiempo aproximado dedicado en esta entrada.')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadMecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZonaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('capacidad', models.PositiveSmallIntegerField(default=5)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='bitacora/')),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.bitacoratrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_ayudantes', models.PositiveSmallIntegerField(default=0, help_text='Número de ayudantes (1 o 2 máx.).')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.especialidadmecanico')),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('ubicacion_fisica', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('OPERATIVA', 'Operativa'), ('EN_MANTENCION', 'En mantención'), ('FUERA_SERVICIO', 'Fuera de servicio')], default='OPERATIVA', max_length=20)),
                ('fecha_adquisicion', models.DateField()),
                ('fecha_ultima_mantencion', models.DateField(blank=True, null=True)),
                ('responsable_asignado', models.ForeignKey(blank=True, help_text='Mecánico responsable de la herramienta.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mecanico')),
            ],
        ),
        migrations.AddField(
            model_name='bitacoratrabajo',
            name='mecanico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mecanico'),
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='core.marcavehiculo')),
            ],
            options={
                'unique_together': {('marca', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('motivo_ingreso', models.CharField(max_length=200)),
                ('descripcion_problema', models.TextField()),
                ('observaciones_iniciales', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('en_lista_espera', models.BooleanField(default=False, help_text='True si la OT está en lista de espera (RF11).')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estadoot')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='HerramientaEnUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.herramienta')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_usadas', to='core.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.CharField(help_text='Encargado de Taller que realiza el control.', max_length=150)),
                ('resultado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=10)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('prueba_ruta_ok', models.BooleanField(default=False)),
                ('fluidos_verificados', models.BooleanField(default=False)),
                ('luces_sistema_electrico_ok', models.BooleanField(default=False)),
                ('herramientas_retiradas', models.BooleanField(default=False)),
                ('vehiculo_limpio', models.BooleanField(default=False)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_calidad', to='core.ordentrabajo')),
            ],
        ),
        migrations.AddField(
            model_name='bitacoratrabajo',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='core.ordentrabajo'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('RECEPCIONISTA', 'Recepcionista'), ('ENCARGADO_TALLER', 'Encargado de Taller'), ('MECANICO', 'Mecánico'), ('ENCARGADO_BODEGA', 'Encargado de Bodega')], max_length=30)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOLICITUD_CAMBIO', 'Solicitud de cambio'), ('ATRASO_TRABAJO', 'Atraso de trabajo'), ('MENSAJE_GENERAL', 'Mensaje general')], max_length=30)),
                ('mensaje', models.TextField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.ordentrabajo')),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to='core.perfilusuario')),
                ('receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_recibidas', to='core.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_compatible', models.CharField(blank=True, max_length=150, null=True)),
                ('compatibilidad', models.CharField(blank=True, help_text='Descripción general de compatibilidad.', max_length=200, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('ubicacion_bodega', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_compra', models.PositiveIntegerField()),
                ('precio_venta', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('DESCONTINUADO', 'Descontinuado')], default='DISPONIBLE', max_length=20)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.PositiveIntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='core.ordentrabajo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.PositiveIntegerField(help_text='Precio aplicado a este servicio.')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.ordentrabajo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('anio', models.PositiveIntegerField()),
                ('kilometraje', models.PositiveIntegerField()),
                ('fecha_ultimo_servicio', models.DateField(blank=True, null=True)),
                ('golpes_observados', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='core.cliente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marcavehiculo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modelovehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehiculo'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='zona_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zonatrabajo'),
        ),
    ]
