# Generated by Django 5.2.5 on 2025-11-30 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='orden',
            field=models.ForeignKey(blank=True, help_text='Puede ser None para notificaciones generales (ej: stock bajo)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.ordentrabajo'),
        ),
    ]
